// Generated by Wrangler by running `wrangler types`

interface Env {
  OAUTH_KV: KVNamespace;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  COOKIE_ENCRYPTION_KEY: string;
  HOSTED_DOMAIN: string;
  MCP_OBJECT: DurableObjectNamespace<import("./src/index").MyMCP>;
}
